cabal-version:      3.14

name:               tva-notifier-worker
version:            0.1.0.0

synopsis:           Notification worker for the tva video-processing service.
description:        Background worker that sends notifications to users about video processing job status updates for the tva service.

license:            MIT
license-file:       ../LICENSE

author:             William Fernandes Dias
maintainer:         william.winchester1967@gmail.com

build-type:         Simple

extra-doc-files:    ../CHANGELOG.md

common warnings
    ghc-options: -Wall

executable tva-notifier-worker
    import:           warnings

    main-is:          Main.hs

    build-depends:    base >=4.17 && <5,
                      tva-core-domain

    hs-source-dirs:   .

    default-language: GHC2021
